<?xml version="1.0" encoding="utf-8"?><Database Name="C:\__WORK\CS\PRJ17\DATAAPP17\SQL\LABSAMPLE.MDF" Class="DB" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=C:\__WORK\CS\PRJ17\LABAPP\STABLE\DB\LABBASE.MDF;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=True" SettingsObjectName="Context.Properties.Settings" SettingsPropertyName="LABBASE_ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Etnos" Member="Etnos">
    <Type Name="Etno">
      <Column Name="EtnoId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="NameEn" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="Etno_Popul" Member="Populs" ThisKey="EtnoId" OtherKey="EtnoId" Type="Popul" />
    </Type>
  </Table>
  <Table Name="dbo.Populs" Member="Populs">
    <Type Name="Popul">
      <Column Name="PopulId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EtnoId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="NameEn" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Codes" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Comment" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Association Name="Popul_Point" Member="Points" ThisKey="PopulId" OtherKey="PopulId" Type="Point" />
      <Association Name="Popul_Anket" Member="Ankets" ThisKey="PopulId" OtherKey="PopulId" Type="Anket" />
      <Association Name="Popul_AnketRel" Member="AnketRels" ThisKey="PopulId" OtherKey="PopulId" Type="AnketRel" />
      <Association Name="Popul_Result" Member="Results" ThisKey="PopulId" OtherKey="PopulId" Type="Result" />
      <Association Name="Etno_Popul" Member="Etno" ThisKey="EtnoId" OtherKey="EtnoId" Type="Etno" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Points" Member="Points">
    <Type Name="Point">
      <Column Name="PointId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PopulId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ExpedId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PointName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Period" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Region" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="RegionEn" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="LocName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="LocX" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="LocY" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Head" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Comment" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Association Name="Point_Anket" Member="Ankets" ThisKey="PointId" OtherKey="PointId" Type="Anket" />
      <Association Name="Popul_Point" Member="Popul" ThisKey="PopulId" OtherKey="PopulId" Type="Popul" IsForeignKey="true" />
      <Association Name="Exped_Point" Member="Exped" ThisKey="ExpedId" OtherKey="ExpedId" Type="Exped" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Expeds" Member="Expeds">
    <Type Name="Exped">
      <Column Name="ExpedId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="DateStart" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="DateEnd" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="Region" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Head" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Info" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Association Name="Exped_Point" Member="Points" ThisKey="ExpedId" OtherKey="ExpedId" Type="Point" />
    </Type>
  </Table>
  <Table Name="dbo.ListTypes" Member="ListTypes">
    <Type Name="ListType">
      <Column Name="Code" Type="System.String" DbType="VarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="ListType_List" Member="Lists" ThisKey="Code" OtherKey="TypeCode" Type="List" />
    </Type>
  </Table>
  <Table Name="dbo.Lists" Member="Lists">
    <Type Name="List">
      <Column Name="ListId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TypeCode" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Item" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Association Name="List_AnketAttr" Member="AnketAttrs" ThisKey="ListId" OtherKey="TypeId" Type="AnketAttr" />
      <Association Name="List_Anket" Member="Ankets" ThisKey="ListId" OtherKey="LinguaId" Type="Anket" />
      <Association Name="List_AnketRel" Member="AnketRels" ThisKey="ListId" OtherKey="LinguaId" Type="AnketRel" />
      <Association Name="List_AnketRel1" Member="AnketRels1" ThisKey="ListId" OtherKey="RelTypeId" Type="AnketRel" />
      <Association Name="List_Sample" Member="Samples" ThisKey="ListId" OtherKey="SampleTypeId" Type="Sample" />
      <Association Name="List_SampleItem" Member="SampleItems" ThisKey="ListId" OtherKey="SampleItemTypeId" Type="SampleItem" />
      <Association Name="List_DnkItem" Member="DnkItems" ThisKey="ListId" OtherKey="ExtractMethodId" Type="DnkItem" />
      <Association Name="List_DnkItem1" Member="DnkItems1" ThisKey="ListId" OtherKey="DnkItemTypeId" Type="DnkItem" />
      <Association Name="ListType_List" Member="ListType" ThisKey="TypeCode" OtherKey="Code" Type="ListType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Places" Member="Places">
    <Type Name="Place">
      <Column Name="PlaceId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(240) NOT NULL" CanBeNull="false" />
      <Column Name="Region" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="Raion" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="Punkt" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="KladrCode" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AnketAttrs" Member="AnketAttrs">
    <Type Name="AnketAttr">
      <Column Name="AttrId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AnketId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Value" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="List_AnketAttr" Member="Type" Storage="_List" ThisKey="TypeId" OtherKey="ListId" Type="List" IsForeignKey="true" />
      <Association Name="Anket_AnketAttr" Member="Anket" ThisKey="AnketId" OtherKey="AnketId" Type="Anket" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Ankets" Member="Ankets">
    <Type Name="Anket">
      <Column Name="AnketId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RUSID" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="GPID" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Fio" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="LivePlace" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="LiveAddress" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="PointId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PopulId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Origin" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="InDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="InPlace" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="BirthDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="BirthPlace" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Man" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="LinguaId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OtherAncestors" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Comment" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Association Name="Anket_AnketAttr" Member="AnketAttrs" ThisKey="AnketId" OtherKey="AnketId" Type="AnketAttr" />
      <Association Name="Anket_AnketDoc" Member="AnketDocs" ThisKey="AnketId" OtherKey="AnketId" Type="AnketDoc" />
      <Association Name="Anket_AnketRel" Member="AnketRels" ThisKey="AnketId" OtherKey="AnketId" Type="AnketRel" />
      <Association Name="Anket_Sample" Member="Samples" ThisKey="AnketId" OtherKey="AnketId" Type="Sample" />
      <Association Name="List_Anket" Member="Lingua" Storage="_List" ThisKey="LinguaId" OtherKey="ListId" Type="List" IsForeignKey="true" />
      <Association Name="Point_Anket" Member="Point" ThisKey="PointId" OtherKey="PointId" Type="Point" IsForeignKey="true" />
      <Association Name="Popul_Anket" Member="Popul" ThisKey="PopulId" OtherKey="PopulId" Type="Popul" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AnketDocs" Member="AnketDocs">
    <Type Name="AnketDoc">
      <Column Name="AnketDocId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AnketId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Link" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="DocType" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Info" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Association Name="Anket_AnketDoc" Member="Anket" ThisKey="AnketId" OtherKey="AnketId" Type="Anket" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AnketRels" Member="AnketRels">
    <Type Name="AnketRel">
      <Column Name="AnketRelId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AnketId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RelTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PopulId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Origin" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="BirthPlace" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="LinguaId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Anket_AnketRel" Member="Anket" ThisKey="AnketId" OtherKey="AnketId" Type="Anket" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="List_AnketRel" Member="Lingua" Storage="_List" ThisKey="LinguaId" OtherKey="ListId" Type="List" IsForeignKey="true" />
      <Association Name="Popul_AnketRel" Member="Popul" ThisKey="PopulId" OtherKey="PopulId" Type="Popul" IsForeignKey="true" />
      <Association Name="List_AnketRel1" Member="RelType" Storage="_List1" ThisKey="RelTypeId" OtherKey="ListId" Type="List" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Stores" Member="Stores">
    <Type Name="Store">
      <Column Name="StoreId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Lab" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Fridge" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="FridgeModule" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="FridgeShelf" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Container" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="Store_Block" Member="Blocks" ThisKey="StoreId" OtherKey="StoreId" Type="Block" />
    </Type>
  </Table>
  <Table Name="dbo.Consts" Member="Consts">
    <Type Name="Const">
      <Column Name="Code" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Samples" Member="Samples">
    <Type Name="Sample">
      <Column Name="SampleId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AnketId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SampleTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SampleCode" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="Sample_SampleItem" Member="SampleItems" ThisKey="SampleId" OtherKey="SampleId" Type="SampleItem" />
      <Association Name="Sample_DnkItem" Member="DnkItems" ThisKey="SampleId" OtherKey="SampleId" Type="DnkItem" />
      <Association Name="Sample_Result" Member="Results" ThisKey="SampleId" OtherKey="SampleId" Type="Result" />
      <Association Name="Anket_Sample" Member="Anket" ThisKey="AnketId" OtherKey="AnketId" Type="Anket" IsForeignKey="true" />
      <Association Name="List_Sample" Member="SampleType" ThisKey="SampleTypeId" OtherKey="ListId" Type="List" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Blocks" Member="Blocks">
    <Type Name="Block">
      <Column Name="BlockId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BlockType" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="BlockCode" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="StoreId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DimX" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DimY" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Block_BlockItem" Member="BlockItems" ThisKey="BlockId" OtherKey="BlockId" Type="BlockItem" />
      <Association Name="Store_Block" Member="Store" ThisKey="StoreId" OtherKey="StoreId" Type="Store" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.BlockItems" Member="BlockItems">
    <Type Name="BlockItem">
      <Column Name="BlockItemId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BlockId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BlockItemCode" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="BlockItem_SampleItem" Member="SampleItems" ThisKey="BlockItemId" OtherKey="BlockItemId" Type="SampleItem" />
      <Association Name="BlockItem_DnkItem" Member="DnkItems" ThisKey="BlockItemId" OtherKey="BlockItemId" Type="DnkItem" />
      <Association Name="Block_BlockItem" Member="Block" ThisKey="BlockId" OtherKey="BlockId" Type="Block" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SampleItems" Member="SampleItems">
    <Type Name="SampleItem">
      <Column Name="SampleItemId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SampleId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SampleItemTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BlockItemId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Comment" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Association Name="BlockItem_SampleItem" Member="BlockItem" ThisKey="BlockItemId" OtherKey="BlockItemId" Type="BlockItem" IsForeignKey="true" />
      <Association Name="Sample_SampleItem" Member="Sample" ThisKey="SampleId" OtherKey="SampleId" Type="Sample" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="List_SampleItem" Member="SampleItemType" ThisKey="SampleItemTypeId" OtherKey="ListId" Type="List" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DnkItems" Member="DnkItems">
    <Type Name="DnkItem">
      <Column Name="DnkItemId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SampleId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DnkItemTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BlockItemId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Concentration" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Quality" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Volume" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="ExtractMethodId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Comment" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Association Name="List_DnkItem" Member="ExtractMethod" ThisKey="ExtractMethodId" OtherKey="ListId" Type="List" IsForeignKey="true" />
      <Association Name="BlockItem_DnkItem" Member="BlockItem" ThisKey="BlockItemId" OtherKey="BlockItemId" Type="BlockItem" IsForeignKey="true" />
      <Association Name="Sample_DnkItem" Member="Sample" ThisKey="SampleId" OtherKey="SampleId" Type="Sample" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="List_DnkItem1" Member="DnkItemType" ThisKey="DnkItemTypeId" OtherKey="ListId" Type="List" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Results" Member="Results">
    <Type Name="Result">
      <Column Name="ResultId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SampleId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ResultType" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="PopulId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Prediction" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Probability" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Haplogroup" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Marker" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Comment" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="GWS1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="GWS2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="B_DYS389I" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="B_DYS389II" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="B_DYS390" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="B_DYS456" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="G_DYS19" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="G_DYS385" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="G_DYS385_2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="G_DYS458" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="R_DYS437" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="R_DYS438" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="R_DYS448" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="R_Y_GATA_H4" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Y_DYS391" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Y_DYS392" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Y_DYS393" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Y_DYS439" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Y_DYS635" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DYS449" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DYS460" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DYS481" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DYS518" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DYS533" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DYS570" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DYS576" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DYS627" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DYF387S1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DYS447" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="Popul_Result" Member="Popul" ThisKey="PopulId" OtherKey="PopulId" Type="Popul" IsForeignKey="true" />
      <Association Name="Sample_Result" Member="Sample" ThisKey="SampleId" OtherKey="SampleId" Type="Sample" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.AnketProcess" Method="AnketProcess">
    <Parameter Name="AnketId" Parameter="anketId" Type="System.Int32" DbType="Int" />
    <Parameter Name="MsgRet" Parameter="msgRet" Type="System.String" DbType="VarChar(100)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.BlockItemsGenerate" Method="BlockItemsGenerate">
    <Parameter Name="BlockId" Parameter="blockId" Type="System.Int32" DbType="Int" />
    <Parameter Name="DimX" Parameter="dimX" Type="System.Int32" DbType="Int" />
    <Parameter Name="DimY" Parameter="dimY" Type="System.Int32" DbType="Int" />
    <Parameter Name="MsgRet" Parameter="msgRet" Type="System.String" DbType="VarChar(100)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.RepSamplesProc" Method="RepSamplesProc">
    <Parameter Name="ExpedId" Parameter="expedId" Type="System.Int32" DbType="Int" />
    <Parameter Name="PopulId" Parameter="populId" Type="System.Int32" DbType="Int" />
    <Parameter Name="SampleCode" Parameter="sampleCode" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="RUSID" Parameter="rUSID" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="GPID" Parameter="gPID" Type="System.String" DbType="VarChar(30)" />
    <ElementType Name="RepSamplesProcResult">
      <Column Name="SampleCode" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ExpedName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="PointRegion" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="EtnoName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="PopulName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="SampleType" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Pol" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="bvLab" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="bvFridge" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="bvFridgeModule" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="bvFridgeShelf" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="bvBlockCode" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="bvBlockItemCode" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="mvLab" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="mvFridge" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="mvFridgeModule" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="mvFridgeShelf" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="mvBlockCode" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="mvBlockItemCode" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="okLab" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="okFridge" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="okFridgeModule" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="okFridgeShelf" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="okBlockCode" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="okBlockItemCode" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="skLab" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="skFridge" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="skFridgeModule" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="skFridgeShelf" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="skBlockCode" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="skBlockItemCode" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="kdLab" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="kdFridge" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="kdFridgeModule" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="kdFridgeShelf" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="kdBlockCode" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="kdBlockItemCode" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="adLab" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="adFridge" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="adFridgeModule" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="adFridgeShelf" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="adBlockCode" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="adBlockItemCode" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="rdLab" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="rdFridge" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="rdFridgeModule" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="rdFridgeShelf" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="rdBlockCode" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="rdBlockItemCode" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ndLab" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ndFridge" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ndFridgeModule" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ndFridgeShelf" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ndBlockCode" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ndBlockItemCode" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="kdConcentration" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="kdQuality1" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="kdQuality2" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="rdQuality1" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="rdQuality2" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="kdVolume" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="rdVolume" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="BirthYear" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EyesColor" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="HairColor" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="EtnoNameY" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="HaploY" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="MarkerY" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="EtnoNameMt" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="HaploMt" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="MarkerMt" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="GWS1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="GWS2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="HasFullGenome" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="HasFoto" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>